apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instagram-backend
  template:
    metadata:
      labels:
        app: instagram-backend
    spec:
      containers:
        - name: backend
          image: idealclone/instagram-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: instagram-backend-service
spec:
  selector:
    app: instagram-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
