version: '3.8'

services:
  instagram-backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: ${DB_HOST}
        DB_NAME: ${DB_NAME}
        DB_PORT: ${DB_PORT}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
    image: idealclone/instagram-backend:${IMAGE_TAG:-dev}
    container_name: instagram-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
